### PR TITLE
Added support for raw queries using sqlalchemy.text()

### PR DESCRIPTION
**Pull request by pvanliefland**
See #9 

Still pretty basic, not sure if this is the way to go...

### CODE REVIEW

**Comment by tomchristie** [comment]
This is looking *really great*!
Very nearly there.

I think we'll want to push these through to the `Connection` interface instead, so that...

* The `Connection` interface continues to mirror the `Database` interface.
* The query building takes place within the connection.

Technically the `connection` isn't currently public interface, but it *will* become so. (See https://github.com/encode/databases/pull/67) Most users won't need it, but we'll allow explicitly grabbing-and-holding a connection if that's what you want to do, in addition to the current style where connections are obtained and released from the pool as needed, and only hang on forcibly if you're within a transaction.

**Comment by pvanliefland** [comment]
Hi! Something like this?

**Comment by tomchristie** [comment]
Looks great! Are query arguments always the `:query_arg` style with this?

(Don't mind either ways what it uses, just thinking about merging and adding some docs for it. Need to make sure I'm saying the right thing.)

**Comment by pvanliefland** [comment]
Yup, just checked the SA docs, I confirm query arguments follow the `:query_arg` style.

I was thinking of adding something like this to the docs, but not sure where:

## Raw queries

In addition to SQLAlchemy core queries, you can also perform raw SQL queries:

```python
# Execute
query = "INSERT INTO notes(text, completed) VALUES (:text, :completed)"
values = {"text": "example1", "completed": True}
await database.execute(query, values)

# Execute many
query = "INSERT INTO notes(text, completed) VALUES (:text, :completed)"
values = [
    {"text": "example2", "completed": False},
    {"text": "example3", "completed": True},
]
await database.execute_many(query, values)

# Fetch multiple rows
query = "SELECT * FROM notes WHERE completed = :completed"
rows = await database.fetch_all(query=query, values={"completed": True})

# Fetch single row
query = "SELECT * FROM notes WHERE id = :id"
result = await database.fetch_one(query=query, values={"id": 1})
```

**Comment by tomchristie** [comment]
Let's do it!
Great work 👏🎉

**Comment by tomchristie** [comment]
Version 0.2.0 released 👍

**Pull request merged**
