### PR TITLE
Replace psycopg2-binary with psycopg2 (#198)

### PR DESCRIPTION
**Pull request by retnikt**

### CODE REVIEW

**Comment by JayH5** [comment]
Just a drive-by comment that this change probably needs a bit of a warning in the changelog as the `psycopg2` package requires build tools, `libpq`, etc, whereas before the `psycopg2-binary` package did not.

**Comment by tomchristie** [comment]
Okay, which makes me want to re-evaluate what benefit this change would give us.

**Comment by retnikt** [comment]
Well, really I think users should have the choice between the binary or non-binary version depending on their circumstances. The only option for this I believe would be to remove the requirement entirely and tell users in the docs that one of them is required for table creation/migrations. This also allows the flexibility of running your migrations entirely separately from your web server.

**Comment by tomchristie** [comment]
Then let's drop `psycopg2` and `pymysql` entirely, and make sure that the next version is a proper version bump, and calls out the requirement to install a sync driver if you're using `alembic` or SQL Alchemy's `engine.create_all()`

**Comment by vmarkovtsev** [comment]
Here I am, the one who released 0.4.0 and broke my own production builds because of this :sweat:

So shall I remove these requirements completely then?

**Pull request merged**
