### PR TITLE
Tweak logging

### PR DESCRIPTION
**Pull request by tomchristie**
* Add `INFO` level connect and disconnect messages.
* Change `DEBUG` messages to single line format.
* Support optional colourized formatting. (Not required, won't impact non-supporting log handlers)

Here's an example of how it looks within a uvicorn context...

Screenshot 2019-10-31 at 15 14 47

Note the database connect and disconnect messages at INFO level, and the DEBUG query messages.

### CODE REVIEW

**Comment by tomchristie** [comment]
Connect/disconnect now highlights the database URL (password obscured).

Allows us to present really nice clear startup info...

Screenshot 2019-10-31 at 15 26 46

**Comment by pvanliefland** [comment]
Great! Just one thought: if I understand correctly, the "Connected to database" means something like "Established connection pool" (except for SQLite, where nothing happens at connection time).

Don't you think it would be useful as well to have logs when a connection is acquired from the pool?

**Comment by tomchristie** [comment]
Potentially yeah. We might consider using TRACE logging level for anything at that kind of level. Certainly transactions and savepoints should be logged at the same DEBUG level as other queries tho. (Maybe they already are - haven’t double checked?)

**Comment by gvbgduh** [comment]
@pvanliefland if I'm not wrong (and at least in asyncpg) the actual connection is done _by the pool_ and seemed that in databases those connections are populated ahead (with the min number) and the pool is rather manager. (But, asyncpg has a particular implementation of that and I'm not 100% sure about other backends.)
So, I'm under impression that that logline appears when the pool is populated with created connections, but more detailed info is probably indeed for the trace level.

**Pull request merged**
