### PR TITLE
fix issue with duplicate column names

### PR DESCRIPTION
**Pull request by ricardomomm**
Hi I'm creating a pull request to allow developers to retrieve data from row using row[table.c.column_name] instead of row['column_name'], while this helps keeping the code mode clean it also fixes issues that I was having when executing selects that were returning duplicated columns: 

`select table1.code, table1.name, table2.code from table1, table2 where table1.code = table2.some_other_code`

### CODE REVIEW

**Comment by ricardomomm** [comment]
Also, I didn't write any unit test covering it as my environment is not fully functional, I'm not a python developer so if you could help me setup this project under windows, I'll be more than welcome to add cover to my changes, and I see that the build is broken, I'll fix and and update the PR

**Comment by ricardomomm** [comment]
Hi, I added automated tests to cover my changes and fixed all things related to formatting.

**Comment by tomchristie** [comment]
Great stuff!

**Comment by tomchristie** [comment]
Released as 0.1.11

**Pull request merged**
