### PR TITLE
mysql asyncmy driver

### LINKED ISSUE #244: Migrate away from aiomysql
`aiomysql` is outdated. The last release is almost 2 years old and there is no support for newer PyMySQL release like 0.10.1 which is the latest one.

There is not ETA for a new release (https://github.com/aio-libs/aiomysql/issues/466) or support for PyMySQL > 0.10.

`aiomysql` is a dependency of `databases` and `databases` is dependency of various web framework for DB support. In the current situation all those web frameworks don't have MySQL support on Fedora (Fedora ships  PyMySQL 0.10) and likely other distributions when installed with the distribution-provided packages.

It would be highly appreciated if you consider to migrate to MySQl binding which are actively maintained.

Thanks

### PR DESCRIPTION
**Pull request by aminalaee**
Fixes #244 .
Adding [asyncmy](https://github.com/long2ice/asyncmy) as another mysql driver which is more up to date and faster in some areas.

- [x]  Adding asyncmy
- [x] Fixing all tests (raw queries are failing)
- [x] Update the docs

### CODE REVIEW

**Comment by aminalaee** [comment]
@dkharyna I'm waiting for feedback.

**Review by gordthompson — APPROVED** [review]
This seems to work fine for me in my little FastAPI test rig at

https://github.com/gordthompson/fastapi-crud-demo

I would prefer that `mysql://…` defaulted to asyncmy instead of aiomysql, but I understand that you might not want to do that right away for fear of breaking stuff. Maybe eventually? (It really does look like the whole "aio*" family of drivers has been orphaned.)

**Comment by aminalaee** [comment]
@gordthompson Thank you for the review.

TBH, I think it would be better to just remove the default database drivers. They can be confusing, we can stick to explicit drivers.

**Comment by aminalaee** [comment]
@tomchristie Friendly reminder :)

**Review by tomchristie — APPROVED** [review]
I'm just going to leave these ones up to your call @aminalaee.

Generally worth trying to keep different aspects into different PRs (Eg. I notice there's some changes to the development scripts here, which really could be kept separate to the `asyncmy` driver addition.) But I'm not bothered enough about that to block this from being able to go in, if you think it's ready.

**Comment by aminalaee** [comment]
> I'm just going to leave these ones up to your call @aminalaee.
> 
> Generally worth trying to keep different aspects into different PRs (Eg. I notice there's some changes to the development scripts here, which really could be kept separate to the `asyncmy` driver addition.) But I'm not bothered enough about that to block this from being able to go in, if you think it's ready.

Thanks for the review. You're right I could leave a little bit of that out of this MR, but as you said it wasn't that much.
Basically I had to edit the actions to allow python coverage for python 3.10 and thought now that I'm here, I'd rather fix this.

Will keep that in mind.

**Comment by tomchristie** [comment]
Yup. To be fair - I do *sometimes* do the same myself. 🤭

**Pull request merged**
