### PR TITLE
Fixed SQLAlchemy DDL statements

### PR DESCRIPTION
**Pull request by FadedCoder**
DDL statements made with SQLAlchemy (such as `sqlalchemy.schema.CreateTable`) used to have issues such as:

```
Traceback (most recent call last):
  File "../database.py", line 50, in <module>
    loop.run_until_complete(prepare_tables())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "../database.py", line 40, in prepare_tables
    resp = await engine.fetch_one(query)
  File "/home/user/Documents/Projects/Python-Projects/test/databases/databases/core.py", line 146, in fetch_one
    return await connection.fetch_one(query, values)
  File "/home/user/Documents/Projects/Python-Projects/test/databases/databases/core.py", line 244, in fetch_one
    return await self._connection.fetch_one(built_query)
  File "/home/user/Documents/Projects/Python-Projects/test/databases/databases/backends/postgres.py", line 159, in fetch_one
    query, args, result_columns = self._compile(query)
  File "/home/user/Documents/Projects/Python-Projects/test/databases/databases/backends/postgres.py", line 205, in _compile
    compiled_params = sorted(compiled.params.items())
AttributeError: 'NoneType' object has no attribute 'items'
```

This PR fixes the issue for `postgres`, `aiopg`, and `mysql` backends.

### CODE REVIEW

**Comment by tomchristie** [comment]
Heya looks like there's a type error being reported by the test suite?... https://github.com/encode/databases/pull/226/checks?check_run_id=868682403#step:6:54

**Comment by FadedCoder** [comment]
> Heya looks like there's a type error being reported by the test suite?... https://github.com/encode/databases/pull/226/checks?check_run_id=868682403#step:6:54

This is a weird one, I'm not able to reproduce it locally...

**Comment by FadedCoder** [comment]
@tomchristie um I tried doing the tests on my PC and both this repo and the master branch has the same error:

```
databases/backends/sqlite.py:81: error: Incompatible types in assignment (expression has type "Connection", variable has type "None")
```

**Comment by FadedCoder** [comment]
Seems like `aiosqlite` added type hinting too (https://github.com/omnilib/aiosqlite/commit/bc94ad9735b8665c51986129a08cd5d060f6708d). I can fix sqlite.py but that'd be a separate PR.

**Comment by vmarkovtsev** [comment]
This closes https://github.com/encode/databases/issues/40

**Comment by vmarkovtsev** [comment]
@FadedCoder The tests still fail, can you PTAL?

**Comment by FadedCoder** [comment]
@vmarkovtsev hey, there was an issue in code formatting (was using autopep8 earlier). Now all the tests pass :D

**Comment by FadedCoder** [comment]
Sure, will implement the changes soon.

**Comment by vmarkovtsev** [comment]
@FadedCoder friendly ping

**Comment by FadedCoder** [comment]
Ah yes, sorry was busy with some work. Will try to push the changes by tomorrow.

**Comment by FadedCoder** [comment]
@vmarkovtsev Implemented the changes :)

By the way, `DDLElement` is a subclass of `ClauseElement` so we don't have to do `typing.Union[ClauseElement, DDLElement]` for strict typing.

**Pull request merged**
