### PR TITLE
Drop Python 3.6

### PR DESCRIPTION
**Pull request by aminalaee**
Dropping Python3.6 and setting minimum version to Python 3.7

### CODE REVIEW

**Review by collerek — APPROVED** [review]

**Comment by collerek** [comment]
@aminalaee This requires changes in checks - 3.6. should be removed from required runs.

**Comment by collerek** [comment]
> The checks are updated for future PRs but since this PR's base branch has that check I think only the maintainer access can merge this. Maybe @tomchristie can help here.

Yep, I believe you need access to settings -> branches to disable it. 
So we indeed need @tomchristie help with that. 
Maybe disable all of them, we don't merge anything that fails any of the runs anyway?

**Comment by aminalaee** [comment]
## 0.6.0 (May 29th, 2022)

* Dropped Python 3.6 support (#458)

### Added

* Add _mapping property to the result set interface (#447 )
* Add contributing docs (#453 )

### Fixed

* Fix query result named access (#448)
* Fix connections getting into a bad state when a task is cancelled (#457)
* Revert #328 parallel transactions (#472)
* Change extra installations to specific drivers (#436)

**Review by Kludex — APPROVED** [review]

**Comment by collerek** [comment]
@Kludex can you adjust the settings of this repository and uncheck the required checks status in the branches settings of `databases`? We cannot merge it since it stills requires python 3.6 check for a branch that removes it.

**Comment by aminalaee** [comment]
@collerek  He mentioned in gitter that only @tomchristie can do that

**Comment by collerek** [comment]
Ah, ok. Saw the operations group in encode and by the description I thought all members can manage repository settings

**Pull request merged**
