### PR TITLE
Version 0.5.4

### PR DESCRIPTION
**Pull request by aminalaee**
https://github.com/encode/databases/releases/edit/untagged-d723639e4d24f39254b7

Changelog:

### Added

 * Support for Unix domain in connections (#423)
 * Added `asyncmy` MySQL driver (#382)

 ### Fixed

 * Fix SQLite fetch queries with multiple parameters (#435)
 * Changed `Record` type to `Sequence` (#408)

### CODE REVIEW

**Comment by aminalaee** [comment]
I guess because of #382 it would make sense to go for 0.6.0.

**Comment by collerek** [comment]
@vmarkovtsev Any chance in helping to push this out? 
You seem to be one of the last active maintainers apart from @aminalaee 😅

**Comment by collerek** [comment]
@tomchristie Can we do anything about helping with the maintenance of this project? 
I know a lot of people switched to sqlalchemy since they introduced async support, yet the databases library is still quite popular and there are very few active maintainers. I can help with reviews if there is no one else that has time for this.

**Comment by tomchristie** [comment]
@collerek - I can add you to @encode/maintainers and walk you through how to perform releases if you'd like?

**Comment by collerek** [comment]
> @collerek - I can add you to @encode/maintainers and walk you through how to perform releases if you'd like?

@tomchristie Sure, happy to help :)

**Comment by tomchristie** [comment]
Okay - invite sent.

What needs doing at the moment?

**Comment by aminalaee** [comment]
We need to approve this PR and release next version: https://github.com/encode/databases/releases/edit/untagged-d723639e4d24f39254b7

**Comment by tomchristie** [comment]
Okay - does someone want to compile the release notes for 0.5.4?
(Even if that's just a comment on this thread, then I can help walk @collerek through the release process.)

**Comment by aminalaee** [comment]
Sure, I'll do that.

**Comment by aminalaee** [comment]
@tomchristie @collerek  I think version 0.6.0 would make more sense here.

**Comment by collerek** [comment]
> @tomchristie @collerek I think version 0.6.0 would make more sense here.

Not sure what is the encode policy here. 
Normally when you reach 1.0.0 it's usually `{breaking}:{feature}:{patch (bug fix)}`.
But before 1.0.0 it's also often `(fixed 0):{breaking}:{feature & bug fix}`

**Comment by tomchristie** [comment]
What @collerek said, yup.
We'd also do a 0.x bump if a feature was big enough to be worth calling out.

**Comment by aminalaee** [comment]
Great, that makes sense. If it get's approved we can do the release.

**Review by tomchristie — APPROVED** [review]

**Pull request merged**
