### PR TITLE
Add support for MySQL unix_socket connection option

### PR DESCRIPTION
**Pull request by coryvirok**
Connection strings that specified `mysql:///db?unix_socket=...` option were not passing the `unix_socket` option to the underlying aiomysql connection. This meant that it was not possible to connect via UNIX domain socket unless the connection option was explicitly given to the `MySQLBackend()` constructor.

This change adds the `unix_socket` connection option to the explicit list of connection options recognized and extracted from the connection string.

### CODE REVIEW

**Comment by coryvirok** [comment]
@tomchristie any chance you or another maintainer can review this? Thanks

**Comment by afgarcia86** [comment]
Bump I could really use this change as well

**Comment by ryanrasti** [comment]
What's the status here? I think `URL` has support for the `unix_sock` parameter which makes this change simpler. I have a PR of my own: #503

**Comment by zanieb** [comment]
Superseded by https://github.com/encode/databases/pull/551

**Pull request closed without merging**
