### PR TITLE
add support rowcount for asyncpg

### PR DESCRIPTION
**Pull request by nicolaichuk**
Please review and merge to upstream.

### CODE REVIEW

**Comment by rafalp** [comment]
Thank you for contributing. Can you update us on what problem those changes solve or what feature they add?

**Comment by nicolaichuk** [comment]
> Thank you for contributing. Can you update us on what problem those changes solve or what feature they add?

@rafalp  This PR add in postgres backends  the ability to get a new value of primary key when a new row is inserted, and the number of rows changed when performing other operations.

You can see the implementation of this behavior for the library here sqlite backends https://github.com/encode/databases/blob/0.7.0/databases/backends/sqlite.py#L134-L136

Please review and merge to upstream.

**Review by rafalp — APPROVED** [review]

**Review by rafalp — CHANGES_REQUESTED** [review]
Those changes look okay, but we should have tests to make sure they work and this behavior doesn't break in future by other PR.

**Comment by zanieb** [comment]
Closing this as stale. Feel free to open again if you want to add tests.

**Pull request closed without merging**
