### PR TITLE
Release 0.4.2

### PR DESCRIPTION
**Pull request by rafalp**
Bumps version number to 0.4.2 and adds release date as 14th March 2021

### CODE REVIEW

**Review by florimondmanca — APPROVED** [review]
LGTM. Are the tests failures known?

**Comment by rafalp** [comment]
@florimondmanca looks like test for aiopg are failing to connect to db, other PostgreSQL driver is working correctly.

**Comment by rafalp** [comment]
I've opened other PR to fix our test runner: https://github.com/encode/databases/pull/297

**Review by euri10 — APPROVED** [review]

**Comment by rafalp** [comment]
Rebased, I'll merge if tests pass.

**Pull request merged**
