### PR TITLE
Issue 249 postponed configuration

### LINKED ISSUE #249: Postponed configuration of database
Session from sqlalchemy [allows](https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.sessionmaker.configure) postponed configuration:
```python
SessionFactory = sessionmaker()
SessionFactory.configure(bind=create_engine('sqlite://'))

session_instance = SessionFactory()
```
Maybe `Database` should be also has `configure` method? This allows to create `Database` object at import time but set parameters for connection (url, pool size, etc) at runtime.

Right now I use FastAPI framework with factory pattern:
```python
def create_app() -> FastAPI:
    app = FastAPI()

    cfg = app.state.cfg = config.parse_config()

    database = app.state.database = create_database(cfg.database)
```
This way I have database instance when handling requests. But I cannot set decorators on function at import time like this because I dont have database instance at import time because I parse config at runtime:
```python
@database.transaction()  # cannot do this
async def create_users(request):
    ...
```
So possible API can be look like this:
```python
database = Database()


def create_app() -> FastAPI:
    app = FastAPI()

    cfg = app.state.cfg = config.parse_config()

    database.initialize(url=cfg.url)

    @app.on_event("startup")
    async def startup():
        await database.connect()

    app.include_route(create_users)


@database.transaction()
async def create_users(request):
    database.execute(create_query)
    return database.fetch_one(query)
```
Also should note, that `configure` method should allow multiple calls, so in tests fixture with `function` scope can recreate ASGI app multiple times (call factory method), which in turn calls `configure`.

### PR DESCRIPTION
**Pull request by artslob**
Closes #249

### CODE REVIEW

**Review by vmarkovtsev — COMMENTED** [review]
This is a big change that touches some of the most critical code and complicates the object lifecycle considerably. I am not even sure we want the deferred configuration in the first place.

**Comment by artslob** [comment]
Yeah, PR and issue are open for discussion to determine whether this PR will be useful. I just think that sometimes its not convenient nor beautiful to parse config at import time. I prefer factory pattern so made this PR.

**Comment by rafalp** [comment]
IMHO there's problem with our API design, but band-aiding it will not help, only make the problem harder to deal with later.

`Core` object wraps the process of strategy creation, but there's no way to extend this process without modifying internals themselves. This bites not only people who need to configure backend-specific extra options not supported by the core, but also those interested in developing support for other databases.

**Comment by artslob** [comment]
Can I do something to improve this PR? Or should I close it then?

**Comment by artslob** [comment]
Maybe create some proxy/wrapper around `Database` class? This way `Database` would not be changed:
```python
class DatabaseWrapper:
    def __init__(self):
        self.db = None

    def configure(self, **all_rapams):
        self.db = Database(**all_rapams)

    def check_configured(self):
        if not self.db:
            raise ValueError

    def connect(self):
        # proxies all methods to inner object
        self.check_configured()
        return self.db.connect()


class Database:
    # this class would not be changed
    pass


db = DatabaseWrapper()


def main():
    params = parse_env_params()
    db.configure(**params)
    connect = db.connect()
```

**Pull request closed without merging**
