### PR TITLE
Fix record iteration

### PR DESCRIPTION
**Pull request by coobas**
Hi again,
I ran into an issue with row columns (`row.keys()` would be empty) from a raw (text) query ('SELECT * FROM ...'). It seems to me it can be fixed by this MR - please have a look. As a side effect I had to adapt some tests for pytest 5, it works with 4.6 as well though.
Cheers
Jakub

### CODE REVIEW

**Comment by tomchristie** [comment]
Looks decent. Would you also be able to include a test case that fails without this change, but passes with it?

**Comment by coobas** [comment]
Of course, a test should have been there! I've added one - and checked it fails when without the fix (https://travis-ci.org/coobas/databases/builds/556169826)

**Comment by tomchristie** [comment]
Looks great! I think the docstring needs a tweak right? I don't think it's quite reflective of what the test is actually for. After that I think we're good to go.

**Comment by tomchristie** [comment]
Alrighty, I've tweaked the docstring. Once Travis completes lets get this in!
Nice one.

**Comment by coobas** [comment]
Thanks, and sorry for the docstring. I just started looking into that + resolving conflicts but you've been faster :)

**Comment by tomchristie** [comment]
Version 0.2.5 now available on PyPI.
Great work!

**Comment by coobas** [comment]
Thanks!

**Pull request merged**
